server:
  port: 8082

spring:
  application:
    name: auth-service
  main:
    allow-circular-references: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/auth_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      default-zone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: auth-service

jwt:
  secret: ${JWT_SECRET:thisIsAVeryLongSecretKeyThatIsGuaranteedToBeAtLeast256BitsLongForTheJWTTokenGeneration1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always