server:
  port: 8082

spring:
  application:
    name: auth-service
  config:
    import: "${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}"
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true
      port: 35729

# Local overrides only (everything else comes from config server)
logging:
  level:
    '[com.employeemgt.auth]': DEBUG