version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: employee-mgt-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-employee_management}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - employee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-employee_management}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Discovery Service
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: employee-mgt-discovery
    ports:
      - "8761:8761"
    networks:
      - employee-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # Config Server
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: employee-mgt-config
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    networks:
      - employee-network
    volumes:
      - ./shared-config-repo:/app/shared-config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: employee-mgt-auth
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - discovery-service
    networks:
      - employee-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${AUTH_DB_URL:-jdbc:postgresql://postgres:5432/auth_service_db}
      - SPRING_DATASOURCE_USERNAME=${AUTH_DB_USERNAME:-admin}
      - SPRING_DATASOURCE_PASSWORD=${AUTH_DB_PASSWORD:-admin123}
      - JWT_SECRET=${JWT_SECRET:-thisIsAVeryLongSecretKeyThatIsGuaranteedToBeAtLeast256BitsLongForTheJWTTokenGeneration1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka

  # Employee Service
  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    container_name: employee-mgt-employee
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - discovery-service
    networks:
      - employee-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${EMPLOYEE_DB_URL:-jdbc:postgresql://postgres:5432/employee_service_db}
      - SPRING_DATASOURCE_USERNAME=${EMPLOYEE_DB_USERNAME:-admin}
      - SPRING_DATASOURCE_PASSWORD=${EMPLOYEE_DB_PASSWORD:-admin123}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: employee-mgt-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - auth-service
      - employee-service
    networks:
      - employee-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - JWT_SECRET=${JWT_SECRET:-thisIsAVeryLongSecretKeyThatIsGuaranteedToBeAtLeast256BitsLongForTheJWTTokenGeneration1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: employee-mgt-zookeeper
    ports:
      - "2181:2181"
    networks:
      - employee-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: employee-mgt-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - employee-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,DOCKER://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092,DOCKER://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  postgres_data:
  kafka_data:
  zookeeper_data:
  zookeeper_logs:

networks:
  employee-network:
    driver: bridge