server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}"
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true
      port: 35731

# Local overrides only (everything else comes from config server)
logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
