# API Gateway Docker Configuration
server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Auth Service Routes
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
           - StripPrefix=0
        
        # Employee Service Routes  
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
          filters:
            - StripPrefix=0

        # Department Service Routes  
        - id: department-service
          uri: lb://employee-service
          predicates:
            - Path=/api/departments/**
          filters:
            - StripPrefix=0

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo=}
  expiration: ${JWT_EXPIRATION:86400000}

# Eureka Configuration for Docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG