server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///app/shared-config-repo
          default-label: main

eureka:
  client:
    service-url:
      default-zone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: config-server

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always